/* Correctly-rounded natural exponential function for bfloat16 value.

Copyright (c) 2025 Maxence Ponsardin and Paul Zimmermann

This file is part of the CORE-MATH project
(https://core-math.gitlabpages.inria.fr/).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include <stdint.h>
#include <errno.h>
#include <math.h> // only used during performance tests
#include <stdio.h>

// Warning: clang also defines __GNUC__
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#endif

#pragma STDC FENV_ACCESS ON

typedef union {__bf16 f; uint16_t u;} b16u16_u;
typedef union {float f;  uint32_t u;} b32u32_u;

/* For 0 <= i1 < 2^8, T1[i1] stores the binary32 approximation of y1=exp(x1)
   to nearest, where the bfloat16 encoding of x1 is (118*2^4+i1)*2^3.
   For example for i1=5, we have x1=0x1.5p-9, which yields 0x1.00a838p+0.
   Table generated by table1() from exp.sage. */
#include "/tmp/T1.h"

/* For 0 <= i2 < 2^7, T2[i2] stores the binary32 approximation of y2=exp(x2)
   to nearest, where the bfloat16 encoding of x1 is (118+h)*2^7+l,
   where i2 decomposes into i2 = h*2^3+l.
   Table generated by table2() from exp.sage. */
#include "/tmp/T2.h"

__bf16 cr_hexp (__bf16 x){
  int bug = x == -0x1.bep-64;
  b16u16_u v = {.f = x};
  // for -0x1p-9 <= x <= 0x1.fep-9, exp(x) rounds to x to nearest
  uint16_t u = v.u, au = u & 0x7fff;
  if (au <= 0x3b00)
    return 1.0f + ((au == u) ? 0x1p-24f : -0x1p-25f); // |x| <= 0x1p-9

  // for x >= 0x1.64p+6, exp(x) > 2^128
  // for x <= -0x1.72p+6, exp(x) < 2^-133
  if (au >= 0x42b9) {
    if (au >= 0x7f80) {
      if (u == 0xff80) return 0;
      return x + x; // Inf or NaN
    }
    return (au == u) ? 0x1.ffp+127f : 0x1p-134f;
  }

  // now 0x3b00 < au < 0x42b9 thus the range of au fits on 11 bits
  // more precisely the exponent part lies in [118,133]
  uint16_t i1 = (au >> 3) - 0x760;
  uint16_t i2 = (((au >> 7) << 3) | (au & 0x7)) - 0x3b0;
  if (bug) printf ("i1=%d i2=%d %a %a\n", i1, i2, T1[i1], T2[i2]);
  float res = T1[i1] * T2[i2];
  return (au == u) ? res : 1.0 / res;
}

// dummy function since GNU libc does not provide it
__bf16 hexp (__bf16 x) {
  return (__bf16) expf ((float) x);
}
