/* Correctly-rounded base-10 exponential biased by 1 for binary16 value.

Copyright (c) 2025 Paul Zimmermann

This file is part of the CORE-MATH project
(https://core-math.gitlabpages.inria.fr/).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#define _GNU_SOURCE // needed to define expf10

#include <stdint.h>
#include <errno.h>
#include <math.h> // only used during performance tests

// Warning: clang also defines __GNUC__
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#endif

#pragma STDC FENV_ACCESS ON

typedef union {_Float16 f; uint16_t u;} b16u16_u;
typedef union {float f;    uint32_t u;} b32u32_u;

/* For 0 <= i1 < 2^11, T1[i1] stores the binary32 approximation of y1=10^x1
   to nearest, where the float16 encoding of x1 is i1*2^5.
   Values y1 that overflow/underflow in binary32 are capped to the
   largest/smallest binary32 value. For encodings that correspond to
   x1=NaN/Inf, we use the same binary32 value.
   Table generated by table1() from exp10m1.sage. */
#include "/tmp/T1.h"

/* For 0 <= i2 < 2^11, T2[i2] stores the binary32 approximation of y2=10^x2
   to nearest, where x2 = (-1)^s*2^(e-25)*l, where i2 decomposes into
   s*2^11+e*2^e+l, with 0 <= s <= 1, 0 <= e, l < 2^5 (with e-24 instead
   of e-25 when e=0), such that any non-singular float16 number x decomposes
   into x1 + x2, where x1 is defined along T1.
   Some values were manually edited to avoid exceptional cases.
   Table generated by table2() from exp10m1.sage. */
#include "/tmp/T2.h"

_Float16 cr_exp10m1f16(_Float16 x){
  b16u16_u v = {.f = x};
  uint16_t u = v.u, au = u & 0x7fff;
  float res;

  if (au < 0x2400) // |x| < 0x1p-6
  {
    // exceptional cases
    switch (u) {
    case 0x8757: return -0x1.0e5ffep-12f; // x = -0x1.d5cp-14
    case 0x9788: return -0x1.14dffep-8f;  // x = -0x1.e2p-10
    case 0xa1fe: return -0x1.b39feap-6f;  // x = -0x1.7f8p-7
    case 0x2147: return 0x1.89800ap-6f;   // x = 0x1.51cp-7
    case 0x2394: return 0x1.1c001ap-5f;   // x = 0x1.e5p-7
    case 0x23fc: return 0x1.2b801p-5f;    // x = 0x1.ffp-7
    }
    /* the Taylor approximation of 10^x-1 around 0 is
       log(10)*x + 1/2*log(10)^2*x^2 + 1/6*log(10)^3*x^3 */
    float t = x;
    float c = 0x1.26bb1cp+1f * t, d;
    d = __builtin_fmaf (c, 0x1.555556p-2 * c, c); // log(10)*x+log(10)^2*x^2/3
    res = __builtin_fmaf (d, 0.5f * c, c);
#ifdef CORE_MATH_SUPPORT_ERRNO
    if (au != 0 && au < 0x1bd) errno = ERANGE; // underflow
#endif
    return res;
  }

  // exceptional cases (switch is faster than consecutive if's)
  switch (u) {
  case 0xa4a8: return -0x1.50000ap-5f; // x = -0x1.2ap-6
  case 0xa4f6: return -0x1.658004p-5f; // x = -0x1.3d8p-6
  case 0x286c: return 0x1.531ff4p-4f;  // x = 0x1.1bp-5
  case 0x24e6: return 0x1.70ffd6p-5f;  // x = 0x1.398p-6
  case 0x2ce8: return 0x1.8b5ffap-3f;  // x = 0x1.3ap-4
  case 0x2d71: return 0x1.badffcp-3f;  // x = 0x1.5c4p-4
  case 0x2615: return 0x1.cc9ffap-5f;  // x = 0x1.854p-6
  case 0x2633: return 0x1.d5bffcp-5f;  // x = 0x1.8ccp-6
  case 0x2ffa: return 0x1.545ffep-2f;  // x = 0x1.fe8p-4
  }

  /* We decompose x into x1 + x2, and use 2^x = 2^x1 * 2^x2,
     where binary32 approximations of 2^x1 and 2^x2 are tabulated. */
  uint16_t i1 = u >> 5;
  uint16_t i2 = ((u >> 10) << 5) | (u & 0x1f);
  res = __builtin_fmaf (T1[i1].f, T2[i2].f, -1.0f);
#ifdef CORE_MATH_SUPPORT_ERRNO
  if (res > 0x1.ffe7c2p+15f) errno = ERANGE; // overflow
#endif
  return res;
}

// dummy function since GNU libc does not provide it
_Float16 exp10m1f16 (_Float16 x) {
  return (_Float16) (exp10f ((float) x) - 1.0f);
}
