stages:
  - test

check:
  stage: test
  image: debian:latest
  before_script:
    - ci/00-prepare-docker.sh
  script:
    - apt-get update -qq && apt-get install -qq build-essential git libmpfr-dev
    # x86-64-v2 is needed for rsqrtq
    - EXTRA_CFLAGS="-march=x86-64-v2 -I/usr/local/include" LDFLAGS="-L/usr/local/lib" ./ci.sh

check_sanitize:
  stage: test
  image: debian:latest
  script:
    - apt-get update -qq && apt-get install -qq build-essential git libmpfr-dev
    - CFLAGS="-fsanitize=undefined -fsanitize=address" LDFLAGS="-fsanitize=undefined -fsanitize=address" ./ci.sh

check_sanitize_clang:
  stage: test
  image: silkeh/clang:latest
  script:
    - apt-get update -qq && apt-get install -qq build-essential git libmpfr-dev
    - CC=clang CORE_MATH_NO_OPENMP=1 CFLAGS=-fsanitize=undefined LDFLAGS=-fsanitize=undefined ./ci.sh

check_without_fma:
  stage: test
  image: debian:latest
  before_script:
    - ci/00-prepare-docker.sh
  script:
    - apt-get update -qq && apt-get install -qq build-essential git
    - EXTRA_CFLAGS="-march=x86-64 -Werror -fsanitize=undefined -fno-sanitize-recover -I/usr/local/include" LDFLAGS="-L/usr/local/lib" ./ci.sh

check_dry:
  stage: test
  image: debian:testing
  before_script:
    - ci/00-prepare-docker.sh
  script:
    - apt-get update -qq && apt-get install -qq build-essential git
    - FORCE=true DRY=--dry LDFLAGS="-L /usr/local/lib" EXTRA_CFLAGS="-I /usr/local/include" ./ci.sh

check_dry_with_O3:
  stage: test
  image: debian:testing
  before_script:
    - ci/00-prepare-docker.sh
  script:
    - apt-get update -qq && apt-get install -qq build-essential git
    - FORCE=true DRY=--dry CFLAGS=-O3 LDFLAGS="-L /usr/local/lib" EXTRA_CFLAGS="-I /usr/local/include" ./ci.sh

check_dry_inexact_errno:
  stage: test
  image: debian:testing
  before_script:
    - ci/00-prepare-docker.sh
  script:
    - apt-get update -qq && apt-get install -qq build-essential git
    - FORCE=true DRY=--dry LDFLAGS="-L /usr/local/lib" EXTRA_CFLAGS="-I /usr/local/include" CFLAGS="-DCORE_MATH_CHECK_INEXACT -DCORE_MATH_SUPPORT_ERRNO" ./ci.sh

check_dry_inexact:
  stage: test
  image: debian:testing
  before_script:
    - ci/00-prepare-docker.sh
  script:
    - apt-get update -qq && apt-get install -qq build-essential git
    - FORCE=true DRY=--dry CFLAGS="-DCORE_MATH_CHECK_INEXACT" LDFLAGS="-L /usr/local/lib" EXTRA_CFLAGS="-I /usr/local/include" ./ci.sh

check_dry_errno:
  stage: test
  image: debian:testing
  before_script:
    - ci/00-prepare-docker.sh
  script:
    - apt-get update -qq && apt-get install -qq build-essential git
    - FORCE=true DRY=--dry CFLAGS="-DCORE_MATH_SUPPORT_ERRNO" LDFLAGS="-L /usr/local/lib" EXTRA_CFLAGS="-I /usr/local/include" ./ci.sh

check_dry_clang:
  stage: test
  image: silkeh/clang:latest
  before_script:
    - ci/00-prepare-docker.sh
  script:
    - apt-get update -qq && apt-get install -qq build-essential git
    - CORE_MATH_NO_OPENMP=1 FORCE=true DRY=--dry CC=clang LDFLAGS="-L /usr/local/lib" EXTRA_CFLAGS="-I /usr/local/include" ./ci.sh

check_dry_icx:
  stage: test
  image: intel/oneapi-hpckit:latest
  before_script:
    - ci/00-prepare-docker.sh
  script:
    - apt-get update -qq && apt-get install -qq build-essential git
    # MPFR-dev is installed in /usr/local
    - FORCE=true DRY=--dry CC=icx LDFLAGS="-L /usr/local/lib" EXTRA_CFLAGS="-I /usr/local/include" ./ci.sh
