stages:
  - test

check:
  stage: test
  image: debian:latest
  script:
    - apt-get update -qq && apt-get install -qq build-essential git libmpfr-dev
    - EXTRA_CFLAGS="-Werror -fsanitize=undefined -fno-sanitize-recover" ./ci.sh

check_without_fma:
  stage: test
  image: debian:latest
  script:
    - apt-get update -qq && apt-get install -qq build-essential git libmpfr-dev
    - EXTRA_CFLAGS="-march=x86-64 -Werror -fsanitize=undefined -fno-sanitize-recover" ./ci.sh

check_dry:
  stage: test
  image: debian:latest
  script:
    - apt-get update -qq && apt-get install -qq build-essential git libmpfr-dev
    - FORCE=true DRY=--dry ./ci.sh

check_dry_without_inex:
  stage: test
  image: debian:latest
  script:
    - apt-get update -qq && apt-get install -qq build-essential git libmpfr-dev
    - FORCE=true DRY=--dry CFLAGS=-O3 ./ci.sh

check_dry_errno:
  stage: test
  image: debian:latest
  script:
    - apt-get update -qq && apt-get install -qq build-essential git libmpfr-dev
    - FORCE=true DRY=--dry CFLAGS="-DCORE_MATH_CHECK_INEXACT -DCORE_MATH_SUPPORT_ERRNO" ./ci.sh

check_dry_clang:
  stage: test
  image: silkeh/clang:latest
  script:
    - apt-get update -qq && apt-get install -qq build-essential git libmpfr-dev
    - CORE_MATH_NO_OPENMP=1 FORCE=true DRY=--dry CC=clang ./ci.sh

check_dry_icx:
  stage: test
  image: intel/oneapi-hpckit:latest
  before_script:
    - ci/00-prepare-docker.sh
  script:
    - apt-get update -qq && apt-get install -qq build-essential git libmpfr-dev
    # MPFR 4.2.1 is installed in /usr/local
    - FORCE=true DRY=--dry CC=icx LDFLAGS="-L /usr/local/lib" EXTRA_CFLAGS="-I /usr/local/include" ./ci.sh
